Specify @folio registry in .npmrc
I failed to get the specifying of the registry in node.js.yml working,
it always failed with:

npm ERR! code E401
npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus
Repository Manager"
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-30T11_01_23_049Z-debug.log
Error: Process completed with exit code 1.

Despite always-auth being set to false.

At least specifying it in .npmrc works!